(load "boothdr.lisp")
(load "exports.lisp")
(load "npextras.lisp")
(load "ptyout.clisp")
(load "btincl2.clisp")
(load "btscan2.clisp")
(load "typrops.clisp")
(load "btpile2.clisp")
(load "typars.clisp")
(load "tyextra.clisp")
(load "tytree1.clisp")
 
(preserve)
