;;This script was created by makelib
(load "try2.lsp")
(in-package "BOOT")
(load_source_database "cclwhereis1.lsp")
(faslout '|ndftip|)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ndftip.lsp")
(faslend)
(faslout '|nepip|)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/nepip.lsp")
(faslend)
(faslout '|noptip|)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/noptip.lsp")
(faslend)
(faslout '|nqip|)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/nqip.lsp")
(faslend)
(faslout '|nrc|)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/nrc.lsp")
(faslend)
(faslout '|nsfip|)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/nsfip.lsp")
(faslend)
(faslout 'ASP1)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP1.NRLIB/code.lsp")
(faslend)
(faslout 'ASP10)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP10.NRLIB/code.lsp")
(faslend)
(faslout 'ASP12)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP12.NRLIB/code.lsp")
(faslend)
(faslout 'ASP19)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP19.NRLIB/code.lsp")
(faslend)
(faslout 'ASP20)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP20.NRLIB/code.lsp")
(faslend)
(faslout 'ASP24)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP24.NRLIB/code.lsp")
(faslend)
(faslout 'ASP27)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP27.NRLIB/code.lsp")
(faslend)
(faslout 'ASP28)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP28.NRLIB/code.lsp")
(faslend)
(faslout 'ASP29)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP29.NRLIB/code.lsp")
(faslend)
(faslout 'ASP30)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP30.NRLIB/code.lsp")
(faslend)
(faslout 'ASP31)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP31.NRLIB/code.lsp")
(faslend)
(faslout 'ASP33)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP33.NRLIB/code.lsp")
(faslend)
(faslout 'ASP34)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP34.NRLIB/code.lsp")
(faslend)
(faslout 'ASP35)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP35.NRLIB/code.lsp")
(faslend)
(faslout 'ASP4)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP4.NRLIB/code.lsp")
(faslend)
(faslout 'ASP41)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP41.NRLIB/code.lsp")
(faslend)
(faslout 'ASP42)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP42.NRLIB/code.lsp")
(faslend)
(faslout 'ASP49)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP49.NRLIB/code.lsp")
(faslend)
(faslout 'ASP50)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP50.NRLIB/code.lsp")
(faslend)
(faslout 'ASP55)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP55.NRLIB/code.lsp")
(faslend)
(faslout 'ASP6)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP6.NRLIB/code.lsp")
(faslend)
(faslout 'ASP7)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP7.NRLIB/code.lsp")
(faslend)
(faslout 'ASP73)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP73.NRLIB/code.lsp")
(faslend)
(faslout 'ASP74)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP74.NRLIB/code.lsp")
(faslend)
(faslout 'ASP77)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP77.NRLIB/code.lsp")
(faslend)
(faslout 'ASP78)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP78.NRLIB/code.lsp")
(faslend)
(faslout 'ASP8)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP8.NRLIB/code.lsp")
(faslend)
(faslout 'ASP80)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP80.NRLIB/code.lsp")
(faslend)
(faslout 'ASP9)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ASP9.NRLIB/code.lsp")
(faslend)
(faslout 'ATTRBUT)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ATTRBUT.NRLIB/code.lsp")
(faslend)
(faslout 'BFUNCT)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/BFUNCT.NRLIB/code.lsp")
(faslend)
(faslout 'D01AGNT)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D01AGNT.NRLIB/code.lsp")
(faslend)
(faslout 'D01AJFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D01AJFA.NRLIB/code.lsp")
(faslend)
(faslout 'D01AKFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D01AKFA.NRLIB/code.lsp")
(faslend)
(faslout 'D01ALFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D01ALFA.NRLIB/code.lsp")
(faslend)
(faslout 'D01AMFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D01AMFA.NRLIB/code.lsp")
(faslend)
(faslout 'D01ANFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D01ANFA.NRLIB/code.lsp")
(faslend)
(faslout 'D01APFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D01APFA.NRLIB/code.lsp")
(faslend)
(faslout 'D01AQFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D01AQFA.NRLIB/code.lsp")
(faslend)
(faslout 'D01ASFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D01ASFA.NRLIB/code.lsp")
(faslend)
(faslout 'D01FCFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D01FCFA.NRLIB/code.lsp")
(faslend)
(faslout 'D01GBFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D01GBFA.NRLIB/code.lsp")
(faslend)
(faslout 'D01TRNS)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D01TRNS.NRLIB/code.lsp")
(faslend)
(faslout 'D01WGTS)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D01WGTS.NRLIB/code.lsp")
(faslend)
(faslout 'D02AGNT)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D02AGNT.NRLIB/code.lsp")
(faslend)
(faslout 'D02BBFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D02BBFA.NRLIB/code.lsp")
(faslend)
(faslout 'D02BHFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D02BHFA.NRLIB/code.lsp")
(faslend)
(faslout 'D02CJFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D02CJFA.NRLIB/code.lsp")
(faslend)
(faslout 'D02EJFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D02EJFA.NRLIB/code.lsp")
(faslend)
(faslout 'D03AGNT)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D03AGNT.NRLIB/code.lsp")
(faslend)
(faslout 'D03EEFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D03EEFA.NRLIB/code.lsp")
(faslend)
(faslout 'D03FAFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/D03FAFA.NRLIB/code.lsp")
(faslend)
(faslout 'DRAW)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/DRAW.NRLIB/code.lsp")
(faslend)
(faslout 'DRAWCFUN)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/DRAWCFUN.NRLIB/code.lsp")
(faslend)
(faslout 'DRAWCURV)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/DRAWCURV.NRLIB/code.lsp")
(faslend)
(faslout 'DRAWPT)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/DRAWPT.NRLIB/code.lsp")
(faslend)
(faslout 'E04AGNT)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/E04AGNT.NRLIB/code.lsp")
(faslend)
(faslout 'E04DGFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/E04DGFA.NRLIB/code.lsp")
(faslend)
(faslout 'E04FDFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/E04FDFA.NRLIB/code.lsp")
(faslend)
(faslout 'E04GCFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/E04GCFA.NRLIB/code.lsp")
(faslend)
(faslout 'E04JAFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/E04JAFA.NRLIB/code.lsp")
(faslend)
(faslout 'E04MBFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/E04MBFA.NRLIB/code.lsp")
(faslend)
(faslout 'E04NAFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/E04NAFA.NRLIB/code.lsp")
(faslend)
(faslout 'E04UCFA)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/E04UCFA.NRLIB/code.lsp")
(faslend)
(faslout 'ESCONT)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ESCONT.NRLIB/code.lsp")
(faslend)
(faslout 'ESCONT1)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ESCONT1.NRLIB/code.lsp")
(faslend)
(faslout 'ESTOOLS)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ESTOOLS.NRLIB/code.lsp")
(faslend)
(faslout 'ESTOOLS1)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ESTOOLS1.NRLIB/code.lsp")
(faslend)
(faslout 'ESTOOLS2)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ESTOOLS2.NRLIB/code.lsp")
(faslend)
(faslout 'GRIMAGE)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/GRIMAGE.NRLIB/code.lsp")
(faslend)
(faslout 'INTFTBL)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/INTFTBL.NRLIB/code.lsp")
(faslend)
(faslout 'INTPACK)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/INTPACK.NRLIB/code.lsp")
(faslend)
(faslout 'NAGC02)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGC02.NRLIB/code.lsp")
(faslend)
(faslout 'NAGC05)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGC05.NRLIB/code.lsp")
(faslend)
(faslout 'NAGC06)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGC06.NRLIB/code.lsp")
(faslend)
(faslout 'NAGD01)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGD01.NRLIB/code.lsp")
(faslend)
(faslout 'NAGD02)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGD02.NRLIB/code.lsp")
(faslend)
(faslout 'NAGD03)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGD03.NRLIB/code.lsp")
(faslend)
(faslout 'NAGE01)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGE01.NRLIB/code.lsp")
(faslend)
(faslout 'NAGE02)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGE02.NRLIB/code.lsp")
(faslend)
(faslout 'NAGE04)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGE04.NRLIB/code.lsp")
(faslend)
(faslout 'NAGF01)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGF01.NRLIB/code.lsp")
(faslend)
(faslout 'NAGF02)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGF02.NRLIB/code.lsp")
(faslend)
(faslout 'NAGF04)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGF04.NRLIB/code.lsp")
(faslend)
(faslout 'NAGF07)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGF07.NRLIB/code.lsp")
(faslend)
(faslout 'NAGS)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGS.NRLIB/code.lsp")
(faslend)
(faslout 'NAGSP)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NAGSP.NRLIB/code.lsp")
(faslend)
(faslout 'NIPROB)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NIPROB.NRLIB/code.lsp")
(faslend)
(faslout 'NUMINT)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/NUMINT.NRLIB/code.lsp")
(faslend)
(faslout 'ODECAT)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ODECAT.NRLIB/code.lsp")
(faslend)
(faslout 'ODEIFTBL)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ODEIFTBL.NRLIB/code.lsp")
(faslend)
(faslout 'ODEPACK)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ODEPACK.NRLIB/code.lsp")
(faslend)
(faslout 'ODEPROB)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ODEPROB.NRLIB/code.lsp")
(faslend)
(faslout 'OPTCAT)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/OPTCAT.NRLIB/code.lsp")
(faslend)
(faslout 'OPTPACK)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/OPTPACK.NRLIB/code.lsp")
(faslend)
(faslout 'OPTPROB)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/OPTPROB.NRLIB/code.lsp")
(faslend)
(faslout 'PDECAT)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/PDECAT.NRLIB/code.lsp")
(faslend)
(faslout 'PDEPACK)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/PDEPACK.NRLIB/code.lsp")
(faslend)
(faslout 'PDEPROB)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/PDEPROB.NRLIB/code.lsp")
(faslend)
(faslout 'ROUTINE)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/ROUTINE.NRLIB/code.lsp")
(faslend)
(faslout 'VIEW)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/VIEW.NRLIB/code.lsp")
(faslend)
(faslout 'VIEW2D)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/VIEW2D.NRLIB/code.lsp")
(faslend)
(faslout 'VIEW3D)
(load "/home/mcd/OpenAxiom/development/int/algebra/unix/VIEW3D.NRLIB/code.lsp")
(faslend)
;; PLEASE DON'T MESS WITH THIS GC CALL. YOU HAVE BEEN WARNED
;; TTT & PAB SUSPECT HASHTABLES ARE BROKEN
(gc)
(save_source_database "cclwhereis2.lsp")
(mapstore 0)  ;; see stats from build process 
(display-keywords)
